name: sadeem_tech_intern
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  curved_labeled_navigation_bar: ^2.0.6
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localization: ^0.3.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  freezed: ^2.5.7
  freezed_annotation: ^2.4.1
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: null
  json_serializable: null
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
